//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_x.Models
{
    using Exam_x.Models.MetaData;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ClassType))]
    public partial class Class
    {
        public int ClassId { get; set; }
        [Required]
        public string Course_Name { get; set; }
        [Required]
        public System.DateTime StartDate { get; set; }
        [Required]
        public string Total_Houre { get; set; }
        [Required]
        public Nullable<int> TeachersId { get; set; }
        

        public virtual Teacher Teacher { get; set; }
    }
}
