//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubjectWebApplictions.Models
{
    using SubjectWebApplictions.Models.MetaData;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(TeacherType))]
    public partial class Teacher
    {
        public int TeacherId { get; set; }
        public string Teacher_Name { get; set; }
        public string Email { get; set; }
        public string Faculty { get; set; }
        public string Picture { get; set; }
        public int SubjectId_ { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
