//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Work_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int TeacherId { get; set; }
        public string Teacher_Name { get; set; }
        public string Email { get; set; }
        public string faculty { get; set; }
        public System.DateTime Class_StartDay { get; set; }
        public int SubjectId { get; set; }
        public string Picture { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
