//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidance_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarId { get; set; }
        public string CarModel { get; set; }
        public System.DateTime ManufacureDate { get; set; }
        public decimal Price_ { get; set; }
        public string Picture { get; set; }
        public int VehicleId { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
